name: ESP32 OTA Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install platformio

      - run: pio run

      - name: Create Release Tag
        run: |
          echo "TAG=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: .pio/build/esp32dev/firmware.bin
